server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: k8s-fake
          __path__: /var/fake-logs/kube.log
    pipeline_stages:
      - json:
          expressions:
            service: service
            environment: env
            level: level
      - labels:
          service:
          environment:
          level:
